name: AWS Changes To Security Groups Ingress or Egress
description: |
  'Hence, ingress and egress settings changes to AWS Security Group should be monitored as these can expose the enviornment to new attack vectors.'
severity: Medium
enabled: false
requiredDataConnectors:
  - connectorId: AWSCloudTrailLogs
    dataTypes:
      - AWSCloudTrailLogs
queryFrequency: 5m
queryPeriod: 5m
suppressionDuration: 5m
triggerOperator: gt
triggerThreshold: 0
incidentConfiguration:
  createIncident: true
  groupingConfiguration: 
    enabled: True
    reopenClosedIncident: False
    lookbackDuration: 5h
    entitiesMatchingMethod: all
    groupByEntities:
tactics:
  - Persistence
relevantTechniques:
query: |
  let timeframe = 1d;
  let EventNameList = dynamic([ "AuthorizeSecurityGroupEgress", "AuthorizeSecurityGroupIngress", "RevokeSecurityGroupEgress", "RevokeSecurityGroupIngress"]);
  AWSCloudTrailLogs
  | where TimeGenerated >= ago(timeframe)
  | where EventName in~ (EventNameList)
  | extend User = iif(isnotempty(UserIdentityUserName), UserIdentityUserName, SessionIssuerUserName)
  | summarize EventCount=count(), StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated) 
  by EventSource, EventName, UserIdentityType, User, SourceIpAddress, UserAgent, SessionMfaAuthenticated, AWSRegion, 
  AdditionalEventData, UserIdentityAccountId, UserIdentityPrincipalid, ResponseElements
  | extend timestamp = StartTimeUtc, AccountCustomEntity = User , IPCustomEntity = SourceIpAddress