name: Stealth:IAMUser/LoggingConfigurationModified
description: |
  'GuardDuty Alert Stealth:IAMUser/LoggingConfigurationModified'
severity: Medium
enabled: false
requiredDataConnectors:
  - connectorId: AWSGuardDutyLog
    dataTypes:
      - AWSGuardDutyLog
queryFrequency: 5m
queryPeriod: 5m
suppressionDuration: 5m
triggerOperator: gt
triggerThreshold: 0
incidentConfiguration:
  createIncident: true
  groupingConfiguration: 
    enabled: True
    reopenClosedIncident: False
    lookbackDuration: 5h
    entitiesMatchingMethod: all
    groupByEntities:
tactics:
relevantTechniques:
query: |
    AWSGuardDutyLog
    | where Type == "Stealth:IAMUser/LoggingConfigurationModified"