name: Modification of Boot Configuration
description: |
  'Identifies use of bcdedit.exe to delete boot configuration data. Malware and attackers sometimes use this tactic as a destructive technique.''
severity: Medium
enabled: false
requiredDataConnectors:
  - connectorId: SecurityEvents
    dataTypes:
      - SecurityEvent
queryFrequency: 5m
queryPeriod: 5m
suppressionDuration: 5m
triggerOperator: gt
triggerThreshold: 0
incidentConfiguration:
  createIncident: true
  groupingConfiguration: 
    enabled: True
    reopenClosedIncident: False
    lookbackDuration: 5h
    entitiesMatchingMethod: all
    groupByEntities:
tactics:
  - DefenseEvasion
relevantTechniques:
  - T1107
query: |
  SecurityEvent
  | where Channel == "Security"
  | where AccountType == "User"
  | where EventID == "4688"
  | where Process == "bcdedit.exe"
  | where CommandLine contains "/set"   
  and CommandLine  contains "bootstatus" 
  or CommandLine contains "no" and CommandLine contains "recoveryenabled"
  | extend AccountCustomEntity = Account 
  | extend HostCustomEntity = Computer